name: Copilot Auto Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main, master ]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  copilot-review:
    name: GitHub Copilot Code Review
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Get PR files
      id: pr-files
      run: |
        # Get list of changed files
        files=$(gh pr view ${{ github.event.pull_request.number }} --json files --jq '.files[].path' | tr '\n' ' ')
        echo "files=$files" >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Request Copilot Review
      run: |
        # Create a review request comment
        gh pr comment ${{ github.event.pull_request.number }} --body "
        🤖 **Copilot Auto-Review Requested**
        
        A comprehensive code review has been requested for this PR. The review will cover:
        
        **📋 Review Criteria:**
        - [ ] **Security**: Vulnerability scanning and security best practices
        - [ ] **Performance**: Code efficiency and optimization opportunities  
        - [ ] **Quality**: Code structure, readability, and maintainability
        - [ ] **Testing**: Test coverage and quality validation
        - [ ] **Documentation**: Code comments and documentation updates
        - [ ] **Standards**: Compliance with project coding standards
        
        **🔍 Files to Review:**
        \`\`\`
        ${{ steps.pr-files.outputs.files }}
        \`\`\`
        
        **⚡ Review Categories:**
        - **Critical**: Must fix (security, functional issues)
        - **Important**: Recommended fixes (performance, maintainability)
        - **Nitpick**: Optional improvements (style, conventions)
        
        Please ensure all **Critical** and **Important** items are addressed before merging.
        
        ---
        *This is an automated review request. Manual review is still recommended.*
        "
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Add review labels
      run: |
        gh pr edit ${{ github.event.pull_request.number }} --add-label "needs-review,copilot-review"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  review-checklist:
    name: Review Checklist Validation
    runs-on: ubuntu-latest
    needs: copilot-review
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Validate PR checklist
      run: |
        # Check if PR body contains required checklist items
        pr_body=$(gh pr view ${{ github.event.pull_request.number }} --json body --jq '.body')
        
        # Check for required sections
        if ! echo "$pr_body" | grep -q "Type of Change"; then
          echo "❌ PR template not used - missing 'Type of Change' section"
          exit 1
        fi
        
        if ! echo "$pr_body" | grep -q "Testing"; then
          echo "❌ PR template not used - missing 'Testing' section"  
          exit 1
        fi
        
        if ! echo "$pr_body" | grep -q "Checklist"; then
          echo "❌ PR template not used - missing 'Checklist' section"
          exit 1
        fi
        
        echo "✅ PR template properly used"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}